/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.0   2017-02-11

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

#include <stdlib.h>

#include "mcu.h"
#include "drivers.h"
#include "helper.h"

static void InitialiseDriver(void)
{
	#define NUMBER_OF_LEDS (4)

	gpioInit_t ledInit =
	{
		SIM_SCGC5_PORTA_MASK,
		{
			BLUE_LED_PORT_A_10,
			ORANGE_LED_PORT_A_11,
			YELLOW_LED_PORT_A_28,
			GREEN_LED_PORT_A_29
		},
		NUMBER_OF_LEDS
	};

	freescale_m4_led_driver.ledInit(&ledInit);
}

static void LedDemo(void)
{
	uint32_t ledPattern[] = {BLUE_LED,GREEN_LED,YELLOW_LED,ORANGE_LED};
	uint32_t led;

	for(led=0;led<sizeof(ledPattern)/sizeof(ledPattern[0]);led++)
	{
		freescale_m4_led_driver.ledOn(ledPattern[led]);
		Delay();
		freescale_m4_led_driver.ledOff(ledPattern[led]);
		Delay();
	}
}

void InterruptLedDemo(void)
{
	static uint32_t ledPattern[] = {BLUE_LED,GREEN_LED,YELLOW_LED,ORANGE_LED};
	static uint32_t state = 0;
	static uint32_t whichLed = 0;

	if(!state)
	{
		freescale_m4_led_driver.ledOn(ledPattern[whichLed]);
	}
	else
	{
		freescale_m4_led_driver.ledOff(ledPattern[whichLed]);
	}

	if(state)
	{
		whichLed++;

		if(whichLed>3)
		{
			whichLed = 0;
		}
	}

	state = !state;
}

int main(void)
{
	InitialiseDriver();
	/* Polled demonstration */
	LedDemo();

	freescale_m4_timer_driver.dvr_SysTickFunction(&InterruptLedDemo);
	freescale_m4_timer_driver.dvr_SysTickInit();
	NVIC_ClearPendingIRQ(abs(SysTick_IRQn));
	NVIC_EnableIRQ(abs(SysTick_IRQn));

	while(1);

    return (0);
}
